version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@2.3.0

jobs:
  run-tests:
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: << parameters.ruby_version >>
    parameters:
      database:
        enum:
          - mysql
          - pg
          - mariadb
          - sqlite3
        type: enum
      redmine_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/migrate-without-plugins
      - redmine-plugin/test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests:
          name: test on newest versions with PostgreSQL
          database: pg
          ruby_version: '2.7'
          redmine_version: 'latest'
      - run-tests:
          name: test on oldest versions with MySQL
          database: mysql
          ruby_version: '2.6'
          redmine_version: '4.2.9'
