version: 2.1

orbs:
  redmine: agileware-jp/redmine-plugin@0.0.10

workflows:
  version: 2
  test:
    jobs:
      - redmine/download:
          name: 'redmine34-download'
          redmine_version: '3.4.11'
      - redmine/test:
          name: 'redmine34-test'
          before-setup:
            - run: touch plugins/redmine_importer/Gemfile # キャッシュ作成のため
            - redmine/generate_database_yml-pg
          executor: redmine/ruby-24-pg
          requires: [redmine34-download]
