version: 2.1

orbs:
  redmine: agileware-jp/redmine-plugin@0.0.14

workflows:
  version: 2
  test:
    jobs:
      - redmine/download:
          name: 'redmine34-download'
          redmine_version: '3.4.11'
      - redmine/test:
          name: 'redmine34-test'
          executor: redmine/ruby-24-pg
          requires: [redmine34-download]
