version: 2.1

orbs:
  redmine: agileware-jp/redmine-plugin@0.0.10

workflows:
  version: 2
  test:
    jobs:
      - redmine/download:
          name: 'redmine40-download'
          redmine_version: '4.0.4'
      - redmine/test:
          name: 'redmine40-test'
          before-setup:
            - run: mv plugins/redmine_importer/Gemfile.local plugins/redmine_importer/Gemfile
            - redmine/generate_database_yml-pg
          executor: redmine/ruby-pg
          requires: [redmine40-download]
