version: 2.1

orbs:
  redmine: agileware-jp/redmine-plugin@0.0.14

workflows:
  version: 2
  test:
    jobs:
      - redmine/download:
          name: 'redmine41-download'
          redmine_version: '4.1.0'
      - redmine/test:
          name: 'redmine41-test'
          executor: redmine/ruby-pg
          requires: [redmine41-download]
